# Default values for wcv9.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Common configuration for all component docker 
Common:
  ReplicaCount: 1
  Cpu: 0.5m
  Memory: 2048Mi
  ## VaultToken specify the Vault token which will be used to connect to Vault server to fetch issue CA or fetch encrypted value based on tenant / env / envtype
  VaultToken: 5b895739-ad95-87d4-9f5a-92bfff799cd0
  ## DBType just will work since 9.0.0.4, because since 9.0.0.4, Commerce V9 start to support mutliple database.
  DBType: db2
  Tenant: demo
  EnvironmentName: qa
  EnvironmentType: auth
  ImageRepo: mycluster.icp:8500/default/
  SPIUserName: spiuser
  SPIUserPWDAES: eNdqdvMAUGRUbiuqadvrQfMELjNScudSp5CBWQ8L6aw=
  SPIUserPWDBase64: c3BpdXNlcjpwYXNzdzByZA==
  NameSpace: default
  ## SessionAffinity is not enable as default, for using it, the connection between store and transaction will passthrough ingress. Meanwhile, the TLS termination is on Ingress. For make the transaction server point
  ## to Loadbalance, you need to provide Loadbalance address.
  SessionAffinity:
        Enable: false
        LoadBalanceAddress:
  VaultURL: http://vault-consul:8200/v1
  ## External Domain use to specify the store-web external domain name which can be recognized by customer's browser. For example. in hostname store.demo4qaauth.ibm.com , ibm.com would be the External Domain name.
  ExternalDomian: ibm.com
  ## CommerceVersion used to specify current OOTB docker image version. By default, it is null
  ## IF you still using 9.0.0.1 and 9.0.0.0, you need to sepcify this version to let template render deployment template with OVERRIDE_PRECONFIG config mode which has be depearted since 9.0.0.2
  CommerceVersion:
  OverridePreconfig: 
  ## IngressSecrete used to specify if need Helm to auto generate the secret for ingress. For production env, customer can choose generate the secret with real CA certification
  IngressSecrete:
    AutoCreate: true
    ReplaceExist: true
  ## PersistenVolumeClaim
  PersistenVolumeClaim:
    AutoCreate: false
    StorageClass: glusterfs
    AccessModes: ReadWriteMany
    StorageSize: 1Gi
    Force: false
    ClearPVC: false 
  ConfigureMode: Vault
  BindingConfigMap: 
  VaultCA:
       Enable: true
       DNSNAME_IN_SubjectAlternativeName: None
       CONTAINER_HOSTNAME: None
  NodeSelector: {}
Tsdb:
  Enable: false
  Name: ts-db
  Replica: 1
  Image: ts-db
  Tag: 9.0.0
  EnvParameters: {}
  NodeSelector: {}
Tsapp:
  Name: ts-app
  Replica: 1
  Image: ts-app
  Tag: 9.0.0
  Merchantkey: eZrWIdOyaDv5FCOTK32Uni288jgIHDv/P9wxhzKmHdiGZ+n8WJ+Ah56uPbfZ9yJWtjQlGczlmr6OgvArFHCgZQ==
  EnvParameters: {}
  NodeSelector: {}
  FileBeatConfigMap:
SearchappMaster:
  Name: search-app-master
  Replica: 1
  Image: search-app
  Tag: 9.0.0
  EnvParameters: {}
  NodeSelector: {}
  FileBeatConfigMap:
SearchappRepeater:
  Name: search-app-repeater
  Replica: 1
  Image: search-app
  Tag: 9.0.0
  EnvParameters: {}
  NodeSelector: {}
  FileBeatConfigMap:
SearchappSlave:
  Name: search-app-slave
  Replica: 1
  Image: search-app
  Tag: 9.0.0  
  EnvParameters: {}
  NodeSelector: {}
  FileBeatConfigMap:
Tsweb:
  Name: ts-web
  Replica: 1
  Image: ts-web
  Tag: 9.0.0
  EnvParameters: {}
  NodeSelector: {}
  FileBeatConfigMap:
Crsapp:
  Name: crs-app
  Image: crs-app
  Tag: 9.0.0
  Replica: 1
  EnvParameters: {}
  NodeSelector: {}
  FileBeatConfigMap:
#Just keep this for support 9.0.0.0 and 9.0.0.1
InitC:
  Image: init-wcs
  Tag: 1.6
SupportC:
  Image: supportcontainer
  Tag: 1.9.6
FileBeat:
  Enable: true
  Image: filebeat
  Tag: 9.0.0.6.3
  ELKServer: ELKServer.cn.ibm.com
